### ISSUE TITLE
Package Feature Checklist

### ISSUE THREAD

**Issue by sfarrens** [CosmoStat/cosmostat#2]
Click on the features you would like this package to include. We can create an issue for every box ticked. Feel free to add items to this list.

## Feature List

- [ ] Unit tests for Python
- [ ] Unit tests for C++
- [ ] Coverage tests for Python
- [ ] Coverage tests for C++
- [ ] Continuous integration (Travis-CI)
- [ ] PyPi package
- [ ] Conda package
- [ ] Homebrew formula
- [ ] Docker image 
- [ ] Stand-alone API documentation for Python
- [ ] Stand-alone API documentation for C++
- [ ] Consolidated API documentation for everything
- [ ] Custom Jekyll website
- [ ] Consolidated Python UI for everything
- [ ] Contribution guidelines
- [ ] Code of conduct
- [ ] Licence
